= Sites de compétition et de cérémonies
:page-aliases: sites-olympiques.adoc

Les Jeux de Milan-Cortina présentent quatre zones de compétition réparties entre la Lombardie, la Vénétie et le Trentin-Haut-Adige.

L'événement s'appuie sur 93 % de sites existants ou temporaires, notamment à Cortina d'Ampezzo où avaient été organisés les Jeux olympiques
d'hiver de 1956. Le stade de biathlon d'Anterselva, les pistes de ski alpin Olimpia delle Tofane à Cortina et la piste du Stelvio à Bormio,
les tremplins Giuseppe-Dal-Ben à Predazzo pour le saut à ski, la piste olympique Eugenio-Monti pour le bobsleigh, la luge et le skeleton,
Val di Fiemme avec le Stade de fond de Lago di Tesero pour le ski nordique en général, ou le Mediolanum Forum de Milan notamment pour
le patinage artistique ont tous déjà accueilli et accueillent encore des épreuves de Coupe du monde ou des championnats du monde
dans les disciplines de neige et de glace.


== Évolutions des sites de compétitions

Le second stade de hockey était dans le plan initial le PalaLido de Milan et a été remplacé par le PalaSharp.

L'ovale de glace posa une problème pour l'organisation. Bien que les compétitions de patinage de vitesse soient prévues par le plan actue
l dans le stade de glace de Baselga di Piné, l'hypothèse de les déplacer à l'Arena Civica de Milan est envisagée, modifiant le règlement
olympique qui prévoit que les compétitions de cette discipline doivent avoir lieu en intérieur. Pour vérifier la faisabilité de ce changement
de lieu, motivé par les coûts exorbitants d'une hypothétique couverture du stade Baselga di Piné et par les doutes du CIO quant à son utilisation
à la fin des compétitions, des tests ont eu lieu en février 2021 à Arena pour tester les caractéristiques de la glace en l'absence de couverture.
Finalement, après avoir envisagé une remise à niveau de l'Oval Lingotto, il fut décidé d'établir un lieu de compétition temporaire à la foire de Milan.

La piste de glisse suscita la controverse en raison de son coût élevé. La reconstruction de la piste olympique Eugenio-Monti et la réhabilitation
de Cesana Pariol furent rejetées pour envisager la compétition en une piste existante à l'étranger.

Bormio a été retenu pour le ski-alpinisme, discipline qui n'était pas au programme des Jeux lors du processus de candidature.
