= Sites olympiques

Les Jeux se déroulent autour de deux sites principaux :

* la ville littorale de Gangneung ;
* le parc des sports d'Alpensia.

== Parc des sports d'Alpensia

La station alpine d'Alpensia Resort dans la commune de Daegwallyeong-myeon est le centre principal des Jeux olympiques de PyeongChang. À l'instar de ce qui avait été fait à Albertville en 1992, une structure temporaire accueille les cérémonies d'ouverture et de clôture.

Le pôle d'Alpensia comprend les installations suivantes :

* Village olympique principal (dôme de Yongpyong) ;
* Stade olympique de PyeongChang : cérémonies d'ouverture et de clôture12 ;
* Centre de saut à ski d'Alpensia : saut à ski, combiné nordique, snowboard (Big air) ;
* Centres de biathlon et de ski de fond d'Alpensia : biathlon, ski de fond et combiné nordique ;
* Centre alpin de Yongpyong : ski alpin (slalom, slalom géant) ;
* Centre de glisse d'Alpensia : luge, bobsleigh et skeleton.

== Pôle du littoral de Gangneung

À l'exception du Centre de curling de Gangneung, toutes les infrastructures du pôle du littoral sont nouvelles et construites pour les Jeux. Leur construction a commencé en juillet 2014, pour un achèvement prévu en octobre 201613. Le coût total de construction de ces patinoires est estimé à 425 millions de dollars US14. Quatre des patinoires sont regroupées dans un parc olympique, tandis que la seconde patinoire de hockey se trouve à l'Université Kwandong.

* Parc olympique de Gangneung
  ** Centre de curling de Gangneung : Curling
  ** Palais des glaces de Gangneung : Short-track et patinage artistique
  ** Centre de hockey de Gangneung : Hockey sur glace (installation temporaire)
  ** Ovale de Gangneung – Patinage de vitesse
* Université Kwandong
  ** Centre de hockey de Kwandong : Hockey sur glace

== Sites olympiques isolés

* Parc de neige de Bokwang
  ** Site de ski acrobatique de Bokwang : Ski acrobatique
  ** Site de snowboard de Bokwang : Snowboard (sauf Big air)
* Centre alpin de Jeongseon (Jungbong) : Ski alpin (descente, Super-G et combiné)
