= Sports au programme

== Nouveautés

En juillet 2021, le CIO propose lors de sa 138e session d'inclure le ski-alpinisme en tant que sport additionnel8 : la nouvelle discipline comptera cinq épreuves (sprints femmes et hommes, courses individuelles femmes et hommes, et relais mixte)9.

La fédération de ski souhaitait intégrer le combiné nordique féminin, dernier sport olympique d'hiver à ne pas être mixte10 ; en effet, un classement féminin est apparu lors de la Coupe du monde 2020-2021. Ce projet a été finalement refusé par la commission exécutive du CIO, tout comme le ski cross par équipe mixte et le snowboard parallèle par équipe mixte11. La FIS avait également émis le souhait12 que le télémark soit représenté.

== Changements

    ski-alpinisme (+3) : nouveau sport olympique avec trois épreuves (sprint hommes, sprint femmes et relais mixte),
    luge (+1 et ch.) : ajout d'une épreuve de double féminin et remplacement d'une épreuve double "open" par une épreuve de double masculin,
    skeleton (+1) : ajout d'une épreuve par équipe mixte,
    saut à ski (+1) : ajout d'une épreuve individuelle féminin sur grand tremplin,
    ski acrobatique (+2) : ajout d'une épreuve bosses en parallèle masculin et féminin,
    ski alpin (-1 et +2) : suppression de l'épreuve parallèle par équipe mixte et ajout des épreuves combiné par équipes masculin et féminin.

== Disciplines

Ces Jeux comprennent 116 épreuves (54 épreuves masculines, 50 féminines et 12 mixtes) pour seize disciplines.
